[package]
name = "algorithm"
version = "0.1.0"
edition = "2024"

build = "build.rs"

[build-dependencies]
swift-bridge-build = "0.1"

[lib]
crate-type = ["staticlib"]

[dependencies]
swift-bridge = "0.1"
rand = "0.9"

[features]
default = []
spm = []
